2025-03-06 16:19:35 - INFO - [__main__] - Script started at 2025-03-06T16:19:35.897248
2025-03-06 16:19:36 - INFO - [__main__] - Using user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
2025-03-06 16:19:41 - ERROR - [__main__] - Error occurred at 2025-03-06T16:19:41.815550
2025-03-06 16:19:41 - ERROR - [__main__] - Message: Failed to create browser instance
2025-03-06 16:19:41 - ERROR - [__main__] - Error code: BROWSER_INIT_ERROR
2025-03-06 16:19:41 - ERROR - [__main__] - Original error: Message: session not created: This version of ChromeDriver only supports Chrome version 134
Current browser version is 133.0.6943.142 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00E9CED3+25523]
	(No symbol) [0x00E223B4]
	(No symbol) [0x00CF06E3]
	(No symbol) [0x00D29F0F]
	(No symbol) [0x00D28F49]
	(No symbol) [0x00D23E6E]
	(No symbol) [0x00D1F3F9]
	(No symbol) [0x00D696DD]
	(No symbol) [0x00D6910A]
	(No symbol) [0x00D5D5F6]
	(No symbol) [0x00D2C55F]
	(No symbol) [0x00D2D8A4]
	GetHandleVerifier [0x011A2713+3193843]
	GetHandleVerifier [0x011B69E9+3276489]
	GetHandleVerifier [0x011B0F0C+3253228]
	GetHandleVerifier [0x00F3B0C0+673184]
	(No symbol) [0x00E2B43D]
	(No symbol) [0x00E28568]
	(No symbol) [0x00E28709]
	(No symbol) [0x00E1AE90]
	BaseThreadInitThunk [0x76047BA9+25]
	RtlInitializeExceptionChain [0x77C2C2EB+107]
	RtlClearBits [0x77C2C26F+191]
Traceback (most recent call last):
  File "c:\Users\corte\OneDrive\Python scripts\polla\test\test.py", line 228, in get_driver
    self._driver = webdriver.Chrome(options=options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 134
Current browser version is 133.0.6943.142 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00E9CED3+25523]
	(No symbol) [0x00E223B4]
	(No symbol) [0x00CF06E3]
	(No symbol) [0x00D29F0F]
	(No symbol) [0x00D28F49]
	(No symbol) [0x00D23E6E]
	(No symbol) [0x00D1F3F9]
	(No symbol) [0x00D696DD]
	(No symbol) [0x00D6910A]
	(No symbol) [0x00D5D5F6]
	(No symbol) [0x00D2C55F]
	(No symbol) [0x00D2D8A4]
	GetHandleVerifier [0x011A2713+3193843]
	GetHandleVerifier [0x011B69E9+3276489]
	GetHandleVerifier [0x011B0F0C+3253228]
	GetHandleVerifier [0x00F3B0C0+673184]
	(No symbol) [0x00E2B43D]
	(No symbol) [0x00E28568]
	(No symbol) [0x00E28709]
	(No symbol) [0x00E1AE90]
	BaseThreadInitThunk [0x76047BA9+25]
	RtlInitializeExceptionChain [0x77C2C2EB+107]
	RtlClearBits [0x77C2C26F+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\corte\OneDrive\Python scripts\polla\test\test.py", line 474, in run
    with self.browser_manager:
         ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\corte\OneDrive\Python scripts\polla\test\test.py", line 243, in __enter__
    self.get_driver()
  File "c:\Users\corte\OneDrive\Python scripts\polla\test\test.py", line 232, in get_driver
    raise ScriptError("Failed to create browser instance", e, "BROWSER_INIT_ERROR")
ScriptError: [BROWSER_INIT_ERROR] Failed to create browser instance Original error: Message: session not created: This version of ChromeDriver only supports Chrome version 134
Current browser version is 133.0.6943.142 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00E9CED3+25523]
	(No symbol) [0x00E223B4]
	(No symbol) [0x00CF06E3]
	(No symbol) [0x00D29F0F]
	(No symbol) [0x00D28F49]
	(No symbol) [0x00D23E6E]
	(No symbol) [0x00D1F3F9]
	(No symbol) [0x00D696DD]
	(No symbol) [0x00D6910A]
	(No symbol) [0x00D5D5F6]
	(No symbol) [0x00D2C55F]
	(No symbol) [0x00D2D8A4]
	GetHandleVerifier [0x011A2713+3193843]
	GetHandleVerifier [0x011B69E9+3276489]
	GetHandleVerifier [0x011B0F0C+3253228]
	GetHandleVerifier [0x00F3B0C0+673184]
	(No symbol) [0x00E2B43D]
	(No symbol) [0x00E28568]
	(No symbol) [0x00E28709]
	(No symbol) [0x00E1AE90]
	BaseThreadInitThunk [0x76047BA9+25]
	RtlInitializeExceptionChain [0x77C2C2EB+107]
	RtlClearBits [0x77C2C26F+191]

2025-03-06 16:19:41 - ERROR - [__main__] - Traceback:
Traceback (most recent call last):
  File "c:\Users\corte\OneDrive\Python scripts\polla\test\test.py", line 228, in get_driver
    self._driver = webdriver.Chrome(options=options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\corte\OneDrive\Python scripts\polla\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 134
Current browser version is 133.0.6943.142 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00E9CED3+25523]
	(No symbol) [0x00E223B4]
	(No symbol) [0x00CF06E3]
	(No symbol) [0x00D29F0F]
	(No symbol) [0x00D28F49]
	(No symbol) [0x00D23E6E]
	(No symbol) [0x00D1F3F9]
	(No symbol) [0x00D696DD]
	(No symbol) [0x00D6910A]
	(No symbol) [0x00D5D5F6]
	(No symbol) [0x00D2C55F]
	(No symbol) [0x00D2D8A4]
	GetHandleVerifier [0x011A2713+3193843]
	GetHandleVerifier [0x011B69E9+3276489]
	GetHandleVerifier [0x011B0F0C+3253228]
	GetHandleVerifier [0x00F3B0C0+673184]
	(No symbol) [0x00E2B43D]
	(No symbol) [0x00E28568]
	(No symbol) [0x00E28709]
	(No symbol) [0x00E1AE90]
	BaseThreadInitThunk [0x76047BA9+25]
	RtlInitializeExceptionChain [0x77C2C2EB+107]
	RtlClearBits [0x77C2C26F+191]


2025-03-06 16:19:45 - INFO - [__main__] - Script completed in 10.02 seconds
